### PR TITLE
apply modern stacks (typescript, lint, prettier) & fix minor erros

### PR DESCRIPTION
**Pull request by helloheesu**
### Why did I make this change
Hi, I was interested in [color-thief](https://github.com/lokesh/color-thief), which is another library written by you, and found this library.
I wanted to use it in typescript environment but it had some lint errors from typescript. So I applied all techniques and fixed the errors.

### Why here?
I thought about creating pull request to original repository by `olivierlesnicki`, but it seems that repository is not maintained any more.
As you're using this library in color-thief, which is still alive and popular, I hope you could review these changes.

### About commit messages..
I followed [gitmoji](https://gitmoji.carloscuesta.me/) convention because I'm used to it and it's a good framework to think of decent commit scale.
But if you think it ruins your commit convention in this repository, please tell me about your convention and I'll apply it to all the commits here.

### CODE REVIEW

**Comment by malko** [comment]
I think it would be nice to put efforts in common there's also one PR on the original repo that need to be included to fix number of color returned by quantize.
What about creating a quantize group for people to contribute as the original project seems dead ?
what do you think @helloheesu  @lokesh ?

**Comment by helloheesu** [comment]
> I think it would be nice to put efforts in common there's also one PR on the original repo that need to be included to fix number of color returned by quantize. What about creating a quantize group for people to contribute as the original project seems dead ? what do you think @helloheesu @lokesh ?

I think that's a great idea. I hope code owner @lokesh would reply :)

**Comment by janishutz** [comment]
@lokesh Looks good to me, I almost started doing this myself, when I saw this PR existed... Well, there are still some conflicts... It would make things easier when developing a TS port of Color-Thief

**Comment by lokesh** [comment]
Old issue, but wanted to say thanks for all the work put into it. I recently made a new release that adopted some of the ideas, including some refactoring, documentation and the addition of tests. I did not take on adding Typescript in this first go as I tackled the low hanging fruit.

https://github.com/lokesh/quantize/pull/5

**Pull request closed without merging**
